version: "3.3"

services:
  parkedns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parkedns
    ports:
      - "8880:80"
    restart: unless-stopped
    # If you need to mount volumes for logs or additional files
    # volumes:
    #   - ./logs:/var/log/nginx
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
